In [1]:
import numpy as np

# Pizza names
pizza_names = np.array([
    "Margherita",
    "Pepperoni",
    "BBQ Chicken",
    "Veggie",
    "Cheese"
])

# Price of each pizza
pizza_prices = np.array([350, 450, 500, 400, 380])

# Quantity sold
pizza_sold = np.array([20, 15, 10, 12, 18])

# Revenue calculation
revenue = pizza_prices * pizza_sold

# Total revenue
total_revenue = np.sum(revenue)

# Total pizzas sold
total_pizzas = np.sum(pizza_sold)

# Average pizzas sold
average_sales = np.mean(pizza_sold)

# Highest selling pizza
max_index = np.argmax(pizza_sold)

print("===== PIZZA SHOP REPORT =====")
print("Pizza Names:", pizza_names)

print("\nRevenue for each pizza:")
for i in range(len(pizza_names)):
    print(f"{pizza_names[i]} = {revenue[i]} Tk")

print("\nTotal Revenue:", total_revenue, "Tk")
print("Total Pizzas Sold:", total_pizzas)
print("Average Sales:", average_sales)

print("\nBest Selling Pizza:")
print(pizza_names[max_index], "-", pizza_sold[max_index], "pieces sold")

===== PIZZA SHOP REPORT =====
Pizza Names: ['Margherita' 'Pepperoni' 'BBQ Chicken' 'Veggie' 'Cheese']

Revenue for each pizza:
Margherita = 7000 Tk
Pepperoni = 6750 Tk
BBQ Chicken = 5000 Tk
Veggie = 4800 Tk
Cheese = 6840 Tk

Total Revenue: 30390 Tk
Total Pizzas Sold: 75
Average Sales: 15.0

Best Selling Pizza:
Margherita - 20 pieces sold


In [2]:
menu = np.array([
    ["Margherita", 350],
    ["Pepperoni", 450],
    ["BBQ Chicken", 500],
    ["Veggie", 400],
    ["Cheese", 380]
])
print("\nMenu:")
for item in menu:
    print(f"{item[0]}: {item[1]} Tk")
    


Menu:
Margherita: 350 Tk
Pepperoni: 450 Tk
BBQ Chicken: 500 Tk
Veggie: 400 Tk
Cheese: 380 Tk


In [3]:
prices_np = np.array([350, 450, 500, 400, 380])
prices_np=prices_np * 1.1  # Increase prices by 10%
print("\nUpdated Prices (after 10% increase):", prices_np)



Updated Prices (after 10% increase): [385. 495. 550. 440. 418.]


In [4]:
empty_array = np.array([])
print("\nEmpty Array:", empty_array)
print("Shape of Empty Array:", empty_array.shape)
single_element_array = np.array([42])
print("\nSingle Element Array:", single_element_array)
print("Shape of Single Element Array:", single_element_array.shape)




Empty Array: []
Shape of Empty Array: (0,)

Single Element Array: [42]
Shape of Single Element Array: (1,)


In [5]:
empty_table = np.zeros((3, 4))
print(empty_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
full_table = np.ones((3, 4))
print(full_table)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
bbx_full = np.full((3, 4), "bbx")
print(bbx_full)

[['bbx' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']]


In [ ]:
bbx_nza[0, 0] = "flour"
print(bbx_nza)

NameError: name 'bbx_box' is not defined