In [1]:
import numpy as np

# Pizza names
pizza_names = np.array([
    "Margherita",
    "Pepperoni",
    "BBQ Chicken",
    "Veggie",
    "Cheese"
])

# Price of each pizza
pizza_prices = np.array([350, 450, 500, 400, 380])

# Quantity sold
pizza_sold = np.array([20, 15, 10, 12, 18])

# Revenue calculation
revenue = pizza_prices * pizza_sold

# Total revenue
total_revenue = np.sum(revenue)

# Total pizzas sold
total_pizzas = np.sum(pizza_sold)

# Average pizzas sold
average_sales = np.mean(pizza_sold)

# Highest selling pizza
max_index = np.argmax(pizza_sold)

print("===== PIZZA SHOP REPORT =====")
print("Pizza Names:", pizza_names)

print("\nRevenue for each pizza:")
for i in range(len(pizza_names)):
    print(f"{pizza_names[i]} = {revenue[i]} Tk")

print("\nTotal Revenue:", total_revenue, "Tk")
print("Total Pizzas Sold:", total_pizzas)
print("Average Sales:", average_sales)

print("\nBest Selling Pizza:")
print(pizza_names[max_index], "-", pizza_sold[max_index], "pieces sold")

===== PIZZA SHOP REPORT =====
Pizza Names: ['Margherita' 'Pepperoni' 'BBQ Chicken' 'Veggie' 'Cheese']

Revenue for each pizza:
Margherita = 7000 Tk
Pepperoni = 6750 Tk
BBQ Chicken = 5000 Tk
Veggie = 4800 Tk
Cheese = 6840 Tk

Total Revenue: 30390 Tk
Total Pizzas Sold: 75
Average Sales: 15.0

Best Selling Pizza:
Margherita - 20 pieces sold


In [2]:
menu = np.array([
    ["Margherita", 350],
    ["Pepperoni", 450],
    ["BBQ Chicken", 500],
    ["Veggie", 400],
    ["Cheese", 380]
])
print("\nMenu:")
for item in menu:
    print(f"{item[0]}: {item[1]} Tk")
    


Menu:
Margherita: 350 Tk
Pepperoni: 450 Tk
BBQ Chicken: 500 Tk
Veggie: 400 Tk
Cheese: 380 Tk


In [3]:
prices_np = np.array([350, 450, 500, 400, 380])
prices_np=prices_np * 1.1  # Increase prices by 10%
print("\nUpdated Prices (after 10% increase):", prices_np)



Updated Prices (after 10% increase): [385. 495. 550. 440. 418.]


In [4]:
empty_array = np.array([])
print("\nEmpty Array:", empty_array)
print("Shape of Empty Array:", empty_array.shape)
single_element_array = np.array([42])
print("\nSingle Element Array:", single_element_array)
print("Shape of Single Element Array:", single_element_array.shape)




Empty Array: []
Shape of Empty Array: (0,)

Single Element Array: [42]
Shape of Single Element Array: (1,)


In [5]:
empty_table = np.zeros((3, 4))
print(empty_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
full_table = np.ones((3, 4))
print(full_table)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
bbx_full = np.full((3, 4), "bbx")
print(bbx_full)

[['bbx' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']]


In [12]:
bbx_full[0, 0] = "flour"
print(bbx_full)

[['flo' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']
 ['bbx' 'bbx' 'bbx' 'bbx']]


In [16]:
surprise = np.random.rand(3, 4)
print("\nSurprise Array (3x4):")
print(surprise)



Surprise Array (3x4):
[[0.683107   0.75702901 0.61298445 0.36718284]
 [0.31377208 0.02565746 0.75942158 0.17522775]
 [0.29290181 0.80278198 0.36736651 0.52676728]]


In [20]:
kids_orders = np.random.randint(1, 5, size=(5, 3))  # 5 kids, 3 pizzas each
print("\nKids' Orders (Random Quantities):")
print(kids_orders)


Kids' Orders (Random Quantities):
[[4 4 3]
 [2 1 4]
 [2 2 1]
 [3 3 4]
 [4 4 4]]


In [21]:
signature_pizza = np.identity(5)
print("\nSignature Pizza (Identity Matrix):")
print(signature_pizza)



Signature Pizza (Identity Matrix):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
delivery_times = np.arange(10, 60, 10)  # Delivery times in minutes
print("\nDelivery Times (10 to 50 minutes):", delivery_times)



Delivery Times (10 to 50 minutes): [10 20 30 40 50]


In [23]:
delivery_times_desc = np.arange(50, 0, -10)
print("\nDelivery Times (Descending):", delivery_times_desc)



Delivery Times (Descending): [50 40 30 20 10]


In [25]:
delivery_times_desc = np.arange(0, 121, 10)
print("\nDelivery Times (Descending):", delivery_times_desc)



Delivery Times (Descending): [  0  10  20  30  40  50  60  70  80  90 100 110 120]


In [26]:
shapes_times = np.linspace(0, 100, num=5)  # 5 evenly spaced delivery times from 0 to 100 minutes
print("\nShapes Times (Evenly Spaced):", shapes_times)


Shapes Times (Evenly Spaced): [  0.  25.  50.  75. 100.]


In [27]:
worker_shifts = np.array(["Morning", "Afternoon", "Evening"])
print("\nWorker Shifts:", worker_shifts)


Worker Shifts: ['Morning' 'Afternoon' 'Evening']


In [29]:
worker_shifts = np.linspace(0, 60, 5)
print("\nWorker Shifts:", worker_shifts)


Worker Shifts: [ 0. 15. 30. 45. 60.]


In [30]:
sales = np.array([1000, 1500, 2000, 2500, 3000])
print("\nSales for each day:", sales)


Sales for each day: [1000 1500 2000 2500 3000]


In [31]:
sales = np.array([1000, 1500, 2000, 2500, 3000])
print("Maximum Sales:", np.max(sales))
print("Minimum Sales:", np.min(sales))
print("Average Sales:", np.mean(sales))
print("Standard Deviation of Sales:", np.std(sales))


Maximum Sales: 3000
Minimum Sales: 1000
Average Sales: 2000.0
Standard Deviation of Sales: 707.1067811865476


In [32]:
sales = np.array([1000, 1500, 2000, 2500, 3000])
print("best sales day:", np.argmax(sales))


best sales day: 4


In [33]:
sales = np.array([1000, 1500, 2000, 2500, 3000])
print("Minimum Sales:", np.min(sales))
print("best sales day:", np.argmin(sales))


Minimum Sales: 1000
best sales day: 0
